define({
  root: ({
    zoom2message: "Click to Zoom to Result",
    addresslabel: "Address",
    coordslabel: "Coordinates",
    addressinsplabel: "Inspector",
    resultslabel: "Results",
    locateDescLabel: "Enter an address:",
    coordDescLabel: "Enter the coordinates:",
    reverseDescLabel: "Use the inspect address tool to click on the map and locate the address",
    removeresultmessage: "Remove Result",
    noresultsfoundlabel: "No Results Found",
    resultsfoundlabel: "Results found:",
    clear: "Clear",
    copytoclipboard: "Copy to clipboard",
    widgetversion: "Enhanced Locate Widget Version Info",
    widgetverstr: "Widget Version",
    wabversionmsg: "Widget is designed to run in Web AppBuilder version",
    revgeocodetip: "Inspect Address by Point",
    coordUnitLbl: "Units:",
    mapSheetLbl: "Map Sheet:",
    example: "Example:",
    locate: "Locate",
    drawpointtooltip: "Inspect Locations Address",
    longitude: "Longitude (X)",
    latitude: "Latitude (Y)",
    coordinates: "Coordinates",
    location: "Location",
    address: "Address",
    exampleClickTooltip: "Click to add the example coordinates above",
    score: "Score",
    locatorissue: "GeocodeServer Issue",
    locatorissuemessage: "GeocodeServer needs to have a singleLineFieldName.",
    limittomapextent: "Limit address search to maps extent.",
    reversegeocodefailtitle: "Address Inspection Failed",
    reversegeocodefailmsg: "Failed to find an address at the location clicked. Please try again.",
    errorInvalidCoordinates: "Invalid coordinates. Please try again.",
    mapInputButton: "Map Input",
    mapInputButtonTitle: "Select coordinates using map",
    mapInputButtonTitleStop: "Stop selecting coordinates using map"
  })
});
