define({
	root : ({
		_widgetLabel : "Draw (ECAN)",
		yes:"Yes",
		no:"No",
		back: "Back",
		selectDrawMode : "Select drawing mode",
		clear : "Clear",
		point : "Point",
		line : "Line",
		polyline : "Polyline",
		freehandPolyline : "Freehand Polyline",
		triangle : "Triangle",
		extent : "Envelope",
		circle : "Circle",
		ellipse : "Ellipse",
		polygon : "Polygon",
		freehandPolygon : "Freehand Polygon",
		text : "Text",
		textWarningMessage : "Text must be written before placing the point on map",
		style : "Style",
		alpha : "Transparency",
		width : "Width",
		size : "Size",
		color : "Color",
		markerColor : "Marker Color",
		outlineColor : "Outline Color",
		lineColor : "Line Color",
		fillColor : "Fill Color",
		showMeasurements : "Show Measurements",
		areaUnits : "Area Units",
		distanceUnits : "Distance Units",
		pointUnits : "Point Units",
		pointUnits : "Units",
		unitMap : "Map Unit",
		unitDMS : "Degres Minutes Seconds Unit",
		unitDD : "Decimal Degres Unit",
		kilometers: "Kilometers",
		miles : "Miles",
		meters : "Meters",
		nauticals : "Nautical miles",
		feet : "Feet",
		yards : "Yards",
		squareKilometers : "Square kilometers",
		squareMiles : "Square miles",
		acres : "Acres",
		hectares : "Hectares",
		squareMeters : "Square meters",
		squareFeet : "Square feet",
		squareYards : "Square yards",
		confirmDrawDelete : "Delete this drawing ?",
		confirmDrawCheckedDelete : "Delete checked drawing ?",
		all : "All",
		draws : 'drawings',
		addDrawTitle : 'Add a drawing',
		editDrawTitle : 'Edit a drawing',
		listDrawTitle : 'Drawings list',
		importExportTitle : 'Import or export drawings',
		exportTitle : "Export drawings",
		importTitle : "Import drawings",
		importErrorMessageNavigator : "Your navigator doesn't support this functionnality.",
		importErrorWarningSelectFile : "Please select a file.",
		importDragAndDropMessage : "Select a file in input or drag and drop a file in this area.",
		importWarningNoDrawings : "No drawings to load",
		importErrorFileStructure : "The file structure doesn't match.",
		importWarningNoExport0Draw : "No export of the file (No drawing to export).",
		importErrorFileName : "The filename you have selected is not supported.",
		importCloseButton:"Close",

		loadDialogTitle:"Load Saved Drawing",
		loadButtonPortal:"Load Drawing",

		settingsTitle:"Drawing Settings",
		settingsDialogTitle:"Drawing Settings",

		drawingName:"Drawing Name",
		drawingDate:"Date Last Modified",

		saveButton : "Save",

		nameField : "Name",
		symbolField : "Symbol",
		nameFieldDefaultValue : "My drawing",
		descriptionField : "Description",
		symbolField : "Symbol",
		localLoading : "Your last drawings were loaded",
		editLabel : "Update this drawing",
		deleteLabel : "Delete this drawing",
		upLabel : "Move this drawing up",
		downLabel : "Move this drawing down",
		zoomLabel : "Zoom on this drawing",
		zoomAllLabel : "Zoom on selected drawings",
		copyLabel : "Copy selected drawings",
		copySuffix : " (copy)",
		cutLabel: "Cut this drawing into multiple pieces",
		reshapeLabel: "Reshape this drawing",
		deleteAllLabel : "Delete selected drawings",
		exportLabel : "Export selected drawings",
		noSelection : "No drawings selected",
		resetButton : "Reset",
		cancelButton : "Cancel",
		textAngle : 'Text Angle',
		fontName : 'Font Name',
		drawSampleRotatedText : 'angle',
		boldTitle : 'Bold',
		boldCharacter : 'B',
		italicTitle : 'Italic',
		italicCharacter : 'I',
		underlineTitle : 'Underline',
		underlineCharacter : 'U',
		addMessage : 'You can now make your drawing on map',
		editMessage : 'NB : you can modify/move geometry on map',
		snappingMessage : 'NB : snapping is allowed (use CTRL)',
		hideOption : 'Hide drawings',
		textPlacement : 'Placement',
		isMeasureMessage:'This label is a measure',
		west:'W',
		east:'E',
		north:'N',
		south:'S',

		drawingCollectionName: "Drawing Features",
    	results: "Results",
        points: "Point Drawings",
	    lines: "Line Drawings",
	    areas: "Area Drawings",

	    mergeLabel: "Merge selected drawings",
	    mergeErrorMixedGeometry: "You cannot merge line and polygon drawings",
	    mergeErrorPointGeometry: "You cannot merge point drawings",
	    mergeErrorMinimumNumber: "You must select at least 2 drawings to merge",

	    explodeLabel: "Explode selected drawings",
	    explodeErrorTextSymbols: "You cannot explode point drawings",
	    explodeErrorMinimumNumber: "You must select at least 1 drawing to explode",

	    bufferLabel: "Buffer selected drawings",
	    bufferErrorPointGeometry: "You cannot buffer label drawings",
	    bufferErrorMinimumNumber: "You must select at least 1 drawing to buffer",
	    bufferModeLabel: 'Buffer',
	    bufferDistanceLabel: 'Distance',
	    bufferCustomDistanceLabel: 'Custom Distance',
	    bufferRingNumberLabel: 'No of Rings',
	    bufferCustomDistanceOptionLabel: 'Custom',
	    bufferMergeLabel: 'Merge',

	    ok: 'OK',
	    cancel: 'Cancel',

	    confirmConvertScaleWarning: "At the current map scale the features you have selected to convert to drawings may have been simplified to make them display more quickly on screen.  \n\nIf you convert them to drawings, the result may not be as spatially accurate as the original source shape.  \n\nIf spatial accuracy is important, please click cancel, and zoom in the map to a closer scale before using the convert to drawing option, otherwise press OK to proceed.",

	    save: {
			saveDialogTitle : "Save Drawings",
			drawingNameLabel : "Drawing Name",
			drawingSnippetLabel: "Summary",
			drawingSnippetPrompt: "Add brief summary of drawing here",
			drawingDescriptionLabel: "Description",
	    	saveLabel: "Save",
	    	savePortalLabel : "Save to Portal",
			exportToFileLabel: "Save to File"
	    },

	    portal: {
	    	confirmPortalDrawingDelete: "Delete this saved drawing?",
	    	drawingAddedMessage: "Drawing has been saved",
	    	drawingAddErrorMessage: "There was a problem saving the drawing",
	    	drawingDeletedMessage: "Drawing has been deleted",
	    	drawingDeleteErrorMessage: "There was a problem deleting the drawing",
	    	drawingExistsMessage: "This drawing exists - do you wish to overwrite it?",
	    	drawingExistsErrorMessage: "There was a problem overwriting the drawing"
	    },

	    search: {
			item: {
		        actions: {
		          add: "Add",
		          delete: "Delete",
		          details: "Details",
		          editDetails: "Edit Details"
		        },
        		typeByOwnerPattern: "{type} by {owner}",	
		        dateFormat: "MMMM d, yyyy",
		        datePattern: "{date}",
		        ratingsCommentsViewsPattern: "{ratings} {ratingsIcon} {comments} {commentsIcon} {views} {viewsIcon}",
		        ratingsCommentsViewsLabels: {"ratings": "ratings", "comments": "comments", "views": "views"},
		        types: {
		          "Feature Collection": "Feature Collection"
		        }        			        
		    }
	    },

	    _featureAction_ConvertToDrawing: "Convert to Drawing"				
	}),
	"ar" : 1,
	"cs" : 1,
	"da" : 1,
	"de" : 1,
	"es" : 1,
	"et" : 1,
	"fi" : 1,
	"fr" : 1,
	"he" : 1,
	"it" : 1,
	"ja" : 1,
	"ko" : 1,
	"lt" : 1,
	"lv" : 1,
	"nb" : 1,
	"nl" : 1,
	"pl" : 1,
	"pt-br" : 1,
	"pt-pt" : 1,
	"ro" : 1,
	"ru" : 1,
	"sv" : 1,
	"th" : 1,
	"tr" : 1,
	"vi" : 1,
	"zh-cn" : 1
});
